### PR TITLE
Add Cradio/Sweep Support

### PR DESCRIPTION
**Pull request by Zylanx**
I added both a left and right keymap for the Cradio/Sweep.
I copied them from the main ZMK repo and then edited the files in to fit with how one of the other board configs in this repo worked.

I also added support for the thumb keys but I am sure the way I did it is probably not the way people here would want it done.
Any suggestions for a better way to do it, such as adding an extra "else if defined" alongside ARTSEY_BIG?

### CODE REVIEW

**Comment by Zylanx** [comment]
I messed up the KEY_* defines on the right hand side, they don't seem to follow the RC defines and I didn't realise that so just quickly testing the correct values for them now

**Comment by mcrosson** [comment]
A couple items I see.

- thank you!
- Is this a big artsey port? I cant quite tell.
- if its a big artsey port can you name it like the corne big artsey port?
- is the thumb var to accomodate the main artsey keymap working with different sized thumb clusters?

**Comment by mcrosson** [comment]
A couple items I see.

- thank you!
- Is this a big artsey port? I cant quite tell.
- if its a big artsey port can you name it like the corne big artsey port?
- is the thumb var to accomodate the main artsey keymap working with different sized thumb clusters?

**Comment by Zylanx** [comment]
So I was going to keep this private but I thought "someone else might also want to use it", so that's why the quality isn't the greatest

It's not a Big Artsey port, the sweep only has 2 thumb keys. I just made it normal artsey and then added an alternate version which had space and enter on the thumb keys. I didn't know what the best way to do it would be with the differently sized thumb clusters. 

I guess I could make that alternate one a big artsey port and then rename it like the corne port and that would fix all of that?

**Pull request merged**
